In [1]:

import pandas as pd
import numpy as np
data = pd.read_csv('sales_subset.csv')

```markdown
# 📝 Домашнее задание: Закрепление работы с Pandas

В этом домашнем задании вам предстоит закрепить навыки предобработки данных, создания новых признаков, группировки и категоризации на основе реальных данных продаж.

**Используемый DataFrame**: `data` (копия исходного датасета продаж).
```

```markdown
### 🛠️ Задание 1. Работа с форматом даты (Datetime)

1. Переведите колонку `date` в формат datetime (если это не было сделано ранее).
2. Создайте новую колонку `is_quarter_end`, которая будет содержать `True`, если дата является концом квартала, и `False` в противном случае (подсказка: используйте атрибут `.dt.is_quarter_end`).
3. Подсчитайте количество записей, которые приходятся на конец квартала.
```

In [17]:
# data['is_quarter_end'] = data['date'].dt.is_quarter_end.astype(int)

data['is_quarter_end'] = np.where (data['date'] > 1, True, False)(int)

TypeError: Invalid comparison between dtype=datetime64[us] and int

In [14]:

data.head()

,Unnamed: 0,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment,is_quarter_end
0,0,1,A,1,2010-02-05,24924.50,False,5.727778,0.679451,8.106,0
1,1,1,A,1,2010-03-05,21827.90,False,8.055556,0.693452,8.106,0
2,2,1,A,1,2010-04-02,57258.43,False,16.816667,0.718284,7.808,0
3,3,1,A,1,2010-05-07,17413.94,False,22.527778,0.748928,7.808,0
4,4,1,A,1,2010-06-04,17558.09,False,27.050000,0.714586,7.808,0

In [9]:
# Ваше решение здесь
data.head()

,Unnamed: 0,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment
0,0,1,A,1,2010-02-05,24924.50,False,5.727778,0.679451,8.106
1,1,1,A,1,2010-03-05,21827.90,False,8.055556,0.693452,8.106
2,2,1,A,1,2010-04-02,57258.43,False,16.816667,0.718284,7.808
3,3,1,A,1,2010-05-07,17413.94,False,22.527778,0.748928,7.808
4,4,1,A,1,2010-06-04,17558.09,False,27.050000,0.714586,7.808

```markdown
### 📊 Задание 2. Категоризация данных (Binning с помощью `pd.cut`)

1. Изучите распределение температуры в колонке `temperature_c` с помощью метода `.describe()`.
2. Разделите температуру на 3 категории (интервала):
   * `cold` (холодно)
   * `warm` (тепло)
   * `hot` (жарко)
   *Границы интервалов определите самостоятельно на основе распределения значений.*
3. Сохраните результат в новую колонку `temp_category`.
4. Выведите количество записей в каждой из полученных категорий.
```

In [3]:
# Ваше решение здесь

```markdown
### 📈 Задание 3. Группировка и Агрегация данных (`groupby`)

1. Сгруппируйте данные по созданной колонке `temp_category`.
2. Для каждой категории температуры найдите:
   * Средние недельные продажи (`weekly_sales`)
   * Общую сумму недельных продаж
3. Отсортируйте полученный результат по убыванию суммы продаж.
```

In [4]:
# Ваше решение здесь

```markdown
### 🌟 Задание 4. Продвинутая группировка

Сгруппируйте данные одновременно по двум колонкам: типу магазина (`type`) и категории температуры (`temp_category`). Найдите медианное значение продаж (`weekly_sales`) для каждого сочетания и сделайте выводы: при какой температуре лучше всего продают магазины разного типа?
```

In [5]:
# Ваше решение здесь

is_hot_day
False    0.84082
True     0.15918
Name: proportion, dtype: float64