In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('sales_subset.csv')

In [3]:
data.head()

,Unnamed: 0,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment
0,0,1,A,1,2010-02-05,24924.50,False,5.727778,0.679451,8.106
1,1,1,A,1,2010-03-05,21827.90,False,8.055556,0.693452,8.106
2,2,1,A,1,2010-04-02,57258.43,False,16.816667,0.718284,7.808
3,3,1,A,1,2010-05-07,17413.94,False,22.527778,0.748928,7.808
4,4,1,A,1,2010-06-04,17558.09,False,27.050000,0.714586,7.808

In [4]:
data.shape

(10774, 10)

In [5]:
%whos

Variable   Type         Data/Info
---------------------------------
data       DataFrame    Shape: (10774, 10)
np         module       <module 'numpy' from 'D:\<...>ges\\numpy\\__init__.py'>
pd         module       <module 'pandas' from 'D:<...>es\\pandas\\__init__.py'>

In [6]:
store_depts = data.drop_duplicates(subset=['store','department'])
store_depts.head()

,Unnamed: 0,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment
0,0,1,A,1,2010-02-05,24924.50,False,5.727778,0.679451,8.106
12,12,1,A,2,2010-02-05,50605.27,False,5.727778,0.679451,8.106
24,24,1,A,3,2010-02-05,13740.12,False,5.727778,0.679451,8.106
36,36,1,A,4,2010-02-05,39954.04,False,5.727778,0.679451,8.106
48,48,1,A,5,2010-02-05,32229.38,False,5.727778,0.679451,8.106

In [7]:
holiday_dates = data[data['is_holiday'] ==True].drop_duplicates(subset='date')['date'].values
holiday_dates

<StringArray>
['2010-09-10', '2011-11-25', '2010-02-12', '2012-09-07', '2010-12-31',
 '2012-02-10', '2011-09-09']
Length: 7, dtype: str

In [8]:
data[data['date'].isin(holiday_dates)].groupby('store')['weekly_sales'].sum().sort_values()

store
14     320.19
19     626.33
20     677.03
39     702.96
31     809.47
13    1284.00
10    1621.41
4     2352.00
6     2822.00
1     3842.47
2     4289.80
27    5875.56
Name: weekly_sales, dtype: float64

In [9]:
data[~data['date'].isin(holiday_dates)].groupby('store')['weekly_sales'].sum().sort_values()

store
39    16112368.16
31    16178440.21
19    18056713.04
1     18824302.08
6     19272878.71
27    21780851.68
10    23176782.48
13    23430084.47
4     23538062.45
2     23781849.54
20    25827640.38
14    26889522.48
Name: weekly_sales, dtype: float64

In [10]:
data.temperature_c.describe()

count    10774.000000
mean        15.731978
std          9.922446
min         -8.366667
25%          7.583333
50%         16.966667
75%         24.166667
max         33.827778
Name: temperature_c, dtype: float64

In [11]:
bins = [-10, -4, 0, 4, 10, 20, 30, 40]
labels = ['frezing', 'very_cold', 'cold', 'normal', 'warm', 'hot', 'very_hot']
data['data_temp_category'] = pd.cut(data['temperature_c'], bins=bins, labels=labels)
data['data_temp_category'].value_counts()

data_temp_category
hot          4134
normal       2455
warm         2292
cold          606
very_cold     599
very_hot      537
frezing       151
Name: count, dtype: int64

In [31]:
data['data_temp_category'] = np.where(data['temperature_c']<0, "otmorozok", '')

In [32]:
data.head()

,Unnamed: 0,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment,data_temp_category,year,month,week_day,is_hot_day,fuel_pice_cat
0,0,1,A,1,2010-02-05,24924.50,False,5.727778,0.679451,8.106,,2010,2,4,False,low
1,1,1,A,1,2010-03-05,21827.90,False,8.055556,0.693452,8.106,,2010,3,4,False,low
2,2,1,A,1,2010-04-02,57258.43,False,16.816667,0.718284,7.808,,2010,4,4,False,low
3,3,1,A,1,2010-05-07,17413.94,False,22.527778,0.748928,7.808,,2010,5,4,False,high
4,4,1,A,1,2010-06-04,17558.09,False,27.050000,0.714586,7.808,,2010,6,4,True,low

In [13]:
revenue_by_temp = data.groupby('data_temp_category')['weekly_sales'].sum()
print(revenue_by_temp)

data_temp_category
             2.375030e+08
otmorozok    1.939168e+07
Name: weekly_sales, dtype: float64

In [14]:
data['store'].value_counts()

store
13    913
20    910
19    906
10    902
1     901
4     901
27    900
2     897
6     894
31    890
14    885
39    875
Name: count, dtype: int64

In [15]:
holiday_sales = (data[data["is_holiday"]].groupby("type")["weekly_sales"].sum())
holiday_sales

type
A    23601.81
B     1621.41
Name: weekly_sales, dtype: float64

In [16]:
data['type'].value_counts(normalize=True)

type
A    0.91628
B    0.08372
Name: proportion, dtype: float64

In [17]:
data['type'].value_counts(normalize=True).sort_values(ascending=False)

type
A    0.91628
B    0.08372
Name: proportion, dtype: float64

In [18]:
# количество строк по каждому отделу, по убыванию
dept_counts = data["department"].value_counts(sort=True)
print(dept_counts)

# количество различных отделов
print(data["department"].nunique())

department
1     144
2     144
3     144
4     144
5     144
     ...
50     72
78     56
77     39
39      7
43      2
Name: count, Length: 80, dtype: int64
80

In [19]:
data['date'] = pd.to_datetime(data['date'])
data.dtypes

Unnamed: 0                       int64
store                            int64
type                               str
department                       int64
date                    datetime64[us]
weekly_sales                   float64
is_holiday                        bool
temperature_c                  float64
fuel_price_usd_per_l           float64
unemployment                   float64
data_temp_category                 str
dtype: object

In [20]:
data['date'] = pd.to_datetime(data['date'])
data['year'] = data['date'].dt.year
data['month'] = data['date'].dt.month
data['week_day'] = data['date'].dt.weekday

In [21]:
data.head(1)

,Unnamed: 0,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment,data_temp_category,year,month,week_day
0,0,1,A,1,2010-02-05,24924.5,False,5.727778,0.679451,8.106,,2010,2,4

In [22]:
for column in ('year','month','week_day'):

    result = data.groupby(column)['weekly_sales'].sum().sort_values(ascending=False)
    print(result)

year
2010    2.377379e+08
2011    1.914128e+07
2012    1.556455e+04
Name: weekly_sales, dtype: float64
month
4     23145345.32
2     22869549.73
12    22633701.31
6     22580284.92
5     21982318.08
7     21718673.59
8     21356872.01
9     21055784.70
3     20898396.14
11    20724885.24
10    19014885.62
1     18914022.24
Name: weekly_sales, dtype: float64
week_day
4    256894718.9
Name: weekly_sales, dtype: float64

In [23]:
data.head()

,Unnamed: 0,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment,data_temp_category,year,month,week_day
0,0,1,A,1,2010-02-05,24924.50,False,5.727778,0.679451,8.106,,2010,2,4
1,1,1,A,1,2010-03-05,21827.90,False,8.055556,0.693452,8.106,,2010,3,4
2,2,1,A,1,2010-04-02,57258.43,False,16.816667,0.718284,7.808,,2010,4,4
3,3,1,A,1,2010-05-07,17413.94,False,22.527778,0.748928,7.808,,2010,5,4
4,4,1,A,1,2010-06-04,17558.09,False,27.050000,0.714586,7.808,,2010,6,4

In [24]:
data['is_hot_day'] = np.where (data['temperature_c'] > 27, True, False)
data.head()

,Unnamed: 0,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment,data_temp_category,year,month,week_day,is_hot_day
0,0,1,A,1,2010-02-05,24924.50,False,5.727778,0.679451,8.106,,2010,2,4,False
1,1,1,A,1,2010-03-05,21827.90,False,8.055556,0.693452,8.106,,2010,3,4,False
2,2,1,A,1,2010-04-02,57258.43,False,16.816667,0.718284,7.808,,2010,4,4,False
3,3,1,A,1,2010-05-07,17413.94,False,22.527778,0.748928,7.808,,2010,5,4,False
4,4,1,A,1,2010-06-04,17558.09,False,27.050000,0.714586,7.808,,2010,6,4,True

In [25]:
data.groupby('year')['is_hot_day'].sum().sort_values(ascending=False)

year
2010    1673
2011      34
2012       8
Name: is_hot_day, dtype: int64

In [26]:
x = 100
if x < 100:
    print('no money')
else:
    print('Millioner')

Millioner

In [27]:
data["fuel_price_usd_per_l"].describe()

count    10774.000000
mean         0.749746
std          0.059494
min          0.664129
25%          0.708246
50%          0.743381
75%          0.781421
max          1.107674
Name: fuel_price_usd_per_l, dtype: float64

In [28]:
bins = [0.6,0.72,0.74,0.78,1.2]
labels = ['low','midle','high','very_high']
data['fuel_pice_cat'] = pd.cut(data["fuel_price_usd_per_l"],bins=bins,labels=labels)
data['fuel_pice_cat'].value_counts()

fuel_pice_cat
low          4617
very_high    3062
high         2497
midle         598
Name: count, dtype: int64

In [29]:
data.groupby(data['unemployment'])['weekly_sales'].sum().sort_values(ascending=Falsef)

NameError: name 'Falsef' is not defined

In [ ]:
data["unemployment"]

In [ ]:
bins = [8.106,8.106,7.808,7.808,7.808]
labels = ['low','midle','high','very_high']
data['unemployment_cat'] = pd.cut(data["unemployment"],bins=bins,labels=labels)
data['unemployment_cat'].value_counts()

In [30]:
holiday_sales = data.groupby("unemployment_cat")["weekly_sales"].sum().sort_values(ascending=False)

KeyError: 'unemployment_cat'

In [ ]:
holiday_sales

In [ ]:
data.head()

In [ ]:
data.groupby(['store','is_holiday'])['weekly_sales'].sum()